# Written by Mark Lammers; Animal Ecology, Vrije Universiteit Amsterdam; marklammers6@gmail.com
# (c) 2018. Released under the terms of the GNU General Public License v3.

# source('C:/Users/mls241/surfdrive/Common_scripts/R_startup_script.R') #VU
# source("C:/DATA/SURFdrive/Common_scripts/R_startup_script.R") #Thuis
# source("E:/SURFdrive/Common_scripts/R_startup_script.R") #Yoga
# 
# setwd(paste(wd.base, '[SURFDRIVE SUBFOLDER]', sep=''))

# Load data and packages
#NA?
debugging<-F


db.files<-function(database.folder, #The folder holding the database files to analyse 
                   split='.',
                   return.dates=F,
                   print.output=T
){
  print('Running db.files.R ...')
  print('This function expects a name for the folder that holds the database files')
  
  wd<-database.folder
  split<-paste(split,collapse='')
  spl<-paste(split)
  spl<-paste('[',split,']',sep='',collapse='')
  
  # Checks before anything can be done
  if(length(wd==1)){
    if(print.output){
      print(paste('Analysing',wd,'using these splits',spl))
    }
  } else {
    print('Input is not a working directory')
    stop()
  }
  
  temp.wd<-getwd()
  setwd(wd)
  
  # Load file names from folder
  files<-list.files(getwd())
  file.infos<-t(sapply(files, file.info))
  files<-files[!unlist(file.infos[,2])] #exclude directories
  
  # Prepare output
  filetypes<-c()
  filenames<-c()
  package.components<-c()
  dates<-c()
  
  # Loop through file names and extract information
  for(f in files){
    # Get components and data type
    components<-unlist(strsplit(f, spl))
    df<-data.frame(components=components)
    df$datatype<-decode.multiple(df$components,target='datatype')
    df$identity<-NA
    
    # Find dates in file names 
    is.date<-df$datatype=='integer' & nchar(df$components)==8
    df$identity[is.date]<-'date'
    
    # Find components generated by the package in file names
    from.package<-c('registry','summary','subjects','fields','values','sources','db','newonly','omitted',
                    'removed','missing','masked','nosource','verify','verification','log','backup')
    by.package<-df$components %in% from.package
    df$identity[by.package]<-'package'
    
    # Find the base filename and extension in file names
    df$identity[is.na(df$identity)]<-'filename'
    df$identity[nrow(df)]<-'filetype'
    filename.base<-paste(df$components[df$identity=='filename'],collapse='.')
    
    # Store output
    filetypes<-unique(c(filetypes,df$components[df$identity=='filetype']))
    filenames<-unique(c(filenames,filename.base))
    package.components<-unique(c(package.components,df$components[df$identity=='package']))
    dates<-unique(c(dates,df$components[df$identity=='date']))
  }
  
  #Also, for every filename, print when it was last updated
  
  # Print output
  if(print.output){
    print(paste('Folder contains',length(files),'files'))
    print(paste('File base names in the folder are:'))
    print(filenames)    
    print(paste('File extensions in the folder are:'))
    print(filetypes)    
    print(paste('Package-generated files in the folder are:'))
    print(package.components)    
    print(paste('Dates on which files were saved in the folder by the package are:'))
    print(dates)
  }
  
  if(return.dates){
    return(dates)
  }
  
  setwd(temp.wd)
}



if(debugging){
  wd<-setwd(paste(wd.base, 'Projects_home/Stokerij/database', sep=''))
  split=c('.','_')
}