# Written by Mark Lammers; Animal Ecology, Vrije Universiteit Amsterdam; marklammers6@gmail.com
# (c) 2018. Released under the terms of the GNU General Public License v3.

# Load data and packages
#NA?
debugging<-F


db.files<-function(database.folder, #The folder holding the database files to analyse 
                   split='.',
                   return.dates=F,
                   print.output=T,
                   quiet=F, #absolutely no information is printed
                   print.help=F #no help message is printed, overridden by quiet flag
){
  if(!quiet){
    cat(note('Running db.files.R ...\n'))
    if(print.help){
      cat(note('This function expects a name for the folder that holds the database files\n'))
    }
  }
  
  split<-paste(split,collapse='')
  spl<-paste(split)
  spl<-paste('[',split,']',sep='',collapse='')
  
  # Checks before anything can be done
  if(length(database.folder==1)){
    wd<-database.folder
    if(!quiet){
      cat(note('Analysing',wd,'using these splits',spl,'\n'))
    }
  } else {
    stop('Input is not a working directory')
  }
  
  # Load file names from folder
  files<-list.files(wd)
  if(length(files)==0){
    stop('The folder is empty')
  }
  file.infos<-t(sapply(files, file.info))
  files<-files[!unlist(file.infos[,2])] #exclude directories
  
  #Store package file name components
  from.package<-c('registry','summary','subjects','fields','values','sources','db','newonly','omitted',
                  'removed','missing','masked','nosource','verify','verification','log','backup')
  
  if(length(files)==0){
    filenames<-NA
    filetypes<-NA
    package.components<-NA
    dates<-NA
  } else {
    
    #Extract file information using apply functions
    options(warn=-1)
    output<-sapply(files,function(f){
      components<-unlist(strsplit(f, spl))
      datatype<-ifelse(!is.na(as.integer(components)),'integer','character')
      df<-data.frame(components=components)
      df$datatype<-datatype
      df$identity<-NA
      
      # Find dates in file names 
      is.date<-df$datatype=='integer' & nchar(df$components)==8
      df$identity[is.date]<-'date'
      
      # Find components generated by the package in file names
      by.package<-df$components %in% from.package
      df$identity[by.package]<-'package'
      
      # Find the base filename and extension in file names
      df$identity[is.na(df$identity)]<-'filename'
      df$identity[nrow(df)]<-'filetype' #overwrites "backup is from package"
      
      return(df)
    })
    options(warn=0)
    
    # Store output
    if(length(files)==1){
      output<-as.data.frame(output[,1])
      filenames<-output[output[,'identity']=='filename','components']
      filetypes<-output[output[,'identity']=='filetype','components']
      package.components<-output[output[,'identity']=='package','components']
      dates<-output[output[,'identity']=='date','components']
    } else {
      filenames<-unique(unname(sapply(mapply(`[`,
                                             output['components',],
                                             sapply(output['identity',],`==`,'filename')),
                                      paste, collapse='.')))
      filetypes<-unique(unname(unlist(mapply(`[`,
                                             output['components',],
                                             sapply(output['identity',],`==`,'filetype')))))
      package.components<-unique(unname(unlist(mapply(`[`,
                                                      output['components',],
                                                      sapply(output['identity',],`==`,'package')))))
      dates<-unique(unname(unlist(mapply(`[`,
                                         output['components',],
                                         sapply(output['identity',],`==`,'date')))))
    }
  }
  
  #Also, for every filename, print when it was last updated
  #TODO
  
  # Print output
  if(print.output){
    cat(note('Folder contains',length(files),'files\n'))
    cat(note('File base names in the folder are:\n'))
    print(filenames)    
    cat(note('File extensions in the folder are:\n'))
    print(filetypes)    
    cat(note('Package-generated files in the folder are:\n'))
    print(package.components)    
    cat(note('Dates on which files were saved in the folder by the package are:\n'))
    print(dates)
  }
  
  if(return.dates){
    return(dates)
  }
  
}



# if(debugging){
#   wd<-setwd(paste(wd.base, 'Projects_home/Stokerij/database', sep=''))
#   split=c('.','_')
# }